server:
  port: 8100



spring:
  application:
    name: cloud-consumer-order



#
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/mb?useUnicode=true&characterEncoding=utf-8&useSSL=false
#
#  hikari:
#    pool-name: DatebookHikariCP
#    connection-timeout: 30000
#    auto-commit: true
#    max-lifetime: 1800000
#    minimum-idle: 5
#    connection-test-query: SELECT 1
#    idle-timeout: 30000
#    maximum-pool-size: 15
#
#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.joker.cloud.com.joker.cloud.payment.payment.entity
#
swagger:
  enable: true
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://www.eureka1.com:7001/eureka/,http://www.eureka2.com:7002/eureka/,http://www.eureka3.com:7003/eureka/
  instance:
    prefer-ip-address: true