server:
  port: 8803

spring:
  application:
    name: cloud-stream-rabbit-consumer
  cloud:
    stream:

      binders:
        defaultRabbit:  # 绑定的名称，用于binding整合
          type: rabbit  #消息组件类型
          environment:  # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest

      bindings:
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json  # 设置消息类型，本次为json;文本则设置为 text/plain
          binder: defaultRabbit  #设置要绑定的消息服务
          group: joker_group



eureka:
  instance:
    lease-renewal-interval-in-seconds: 2 #心跳频率
    lease-expiration-duration-in-seconds: 5 #超过多少秒没发心跳包
    instance-id: receive-8803.com
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://www.eureka1.com:7001/eureka
    register-with-eureka: true
    fetch-registry: true