server:
  port: 8002



spring:
  application:
    name: cloud-provider-payment


  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mb?useUnicode=true&characterEncoding=utf-8&useSSL=false

  hikari:
    pool-name: DatebookHikariCP
    connection-timeout: 30000
    auto-commit: true
    max-lifetime: 1800000
    minimum-idle: 5
    connection-test-query: SELECT 1
    idle-timeout: 30000
    maximum-pool-size: 15

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.joker.cloud.entity

swagger:
  enable: true
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka1.com:7001/eureka/
      #defaultZone: http://www.eureka1.com:7001/eureka/,http://www.eureka2.com:7002/eureka/,http://www.eureka3.com:7003/eureka/
    healthcheck:
      enabled: true
  instance:
    instance-id: payment8002
    prefer-ip-address: true # 将自己的IP地址注册到注册中心

